atinfo/awesome-test-automation

java-test-automation.md

Extended Code analysis / Windows UI test automation / Build tools / CI / Reporting sections.

Added new links

---

java-test-automation.md

1) Added new CI link.
2) Removed redundant whitespaces.
3) Added missing dots.
4) Fixed spelling.
5) Added SikuliX into linux / mac / web sections, as it's a cross-platform / functional tool.

New link + minor updates

---

java-test-automation.md

Added some information about 
1. Thucydides library
2. Habr information about structure

# Resources

---

java-test-automation.md

Added MBT section containing GraphWalker

Add MBT section

---

python-test-automation.md

See https://github.com/guykisel/robotframework-faker

Add robotframework-faker

---

.gitignore
php-test-automation.md

Also patched gitignore for those who use IDE to edit this project

Added lots of PHP testing / qa tools

---

c#-test-automation.md
python-test-automation.md

to c#-test-automation for WinForms and WPF applications
to python-test-automation for Windows Store Apps and WinForms/WPF applications too

Add Winium info

---

java-test-automation.md

Recently Thucydides project has been renamed to Serenity BDD.

Update on Thucydides project name

---

python-test-automation.md

pywinauto 0.5.0 released, so adding to the list

Add pywinauto to Windows UI test automation tools

---

java-test-automation.md

Please add Satisfy framework link.

Add Satisfy Framework link

---

java-test-automation.md

- add selenium-grid-extensions repo to the list of extensions

Add Selenium Grid Extensions

---

c#-test-automation.md
python-test-automation.md

Added REST API Testing Section

Added REST API Testing Section

---

java-test-automation.md

add Winium for Desktop

---

python-test-automation.md

add Needle for python

---

automation-and-testing-as-service.md

I have added links to Security testing under "awesome-test-automation/automation-and-testing-as-service.md" 
Please verify and approve if you feel it's right and useful for others.

Added Security testing

---

java-test-automation.md

add Genie plugin

---

mobile-test-automation.md

Add Macaca

---

ruby-test-automation.md

Added Mobile Testing Tool Under Mobile Test Automation

Added Mobile Testing Tool Under Mobile Test Automation

---

javascript-test-automation.md

Added cucumberjs which is popular right now in BDD section of test automation with javascript.

CucumberJS BDD to javascript test automation

---

javascript-test-automation.md

Added ESLint code checker to the javascript tools, see [eslint](https://github.com/eslint/eslint).

ESLint to javascript-test-automation.md

---

javascript-test-automation.md

add npm vulnerability scanner

---

javascript-test-automation.md

https://github.com/segmentio/nightmare

Add Nightmare

---

javascript-test-automation.md

Add Gemini and Hermione tools

---

javascript-test-automation.md

Added chai (BDD framework), RobotJS (Desktop Automation) & JSDoc3, Docco, Mr-Doc, YUIDoc documentation generators

add chai,robot,doc tools

---

java-test-automation.md
python-test-automation.md

added awesome-robotframework list

---

automation-and-testing-as-service.md
general-purpose-test-automation-tools.md
javascript-test-automation.md

k6: https://github.com/loadimpact/k6
Load Impact: https://loadimpact.com/

Added k6 and Load Impact references

---

general-purpose-test-automation-tools.md

Added OWASP Glue for Security Automation

---

javascript-test-automation.md

Add ESDoc to Documentation section

Add ESDoc to Documentation section

---

javascript-test-automation.md

These two are the most popular reporting solutions for end-to-end tests.

Add more Javascript reporters

---

java-test-automation.md

Added  #76, #83, #103, #135, #136 from the Issues. Removed a ton of trailing white space. 
Let me know if things should be shuffled around. Used my best judgment of where I think things should be placed.

Some Issues Taken care. Include  #76, #83, #103, #135, #136

---

javascript-test-automation.md

- Where possible I've added links to the dedicated web pages instead of the GitHub repo
- When available I've added the https variant
- Fixed formatting issue in `Documentation generation`
- Fixed 404 for WebdriverJS, Macaca and Komodo IDE
- Replaced two dashes that were wider than the rest
According to the guidelines, here is a high five: 🖐

docs(javascript): update various links and fix formatting issue

---

ruby-test-automation.md

More about the knapsack gem:
https://github.com/ArturT/knapsack
https://rubygems.org/gems/knapsack

Ruby: Add knapsack for optimal test suite parallelisation across CI nodes

---

java-test-automation.md

"JGiven" was added to "Java test automation --> TDD \ ATDD \ BDD"

Updated the "Java test automation"

---

java-test-automation.md

ReportPorta.io in Reporting section

---

javascript-test-automation.md
python-test-automation.md

Added SikuliX into Python & JavaScript pages as it can be **used** for testing both and scripted in both.

#169:Added sikulix to Javascript & python lists for UI testing.

---

java-test-automation.md

Adding Zalenium

---

javascript-test-automation.md

Hi @polusok thanks for creating the issue. I'm adding some new tools that are base on headless + visible Chrome. The descriptions are base on below review. Let me know if the format is not ok I can re-edit, or feel free to re-edit directly. Thanks!
Only the AutoGCD tool I left out because it is based on Go language and I don't think there is any appropriate place on the awesome list to add that entry at this point in time.
https://medium.com/@kensoh/chromeless-chrominator-chromy-navalia-lambdium-ghostjs-autogcd-ef34bcd26907

#175 - new entrants for headless + visible Chrome

---

java-test-automation.md

Updated outdated items, added some new.

Java section updates

---

javascript-test-automation.md

Couple frameworks moved to correct subgroups
Moved to correct group WebdriverJS and WebdriverIO
Updated descriptions

Updated Test runners section

---

javascript-test-automation.md

I suggest to add **Benchmarks** sub-section for test-runners comparison tools and resources.
Thanks in advance!

Add js-testrunners-bench

---

general-purpose-test-automation-tools.md
java-test-automation.md

Added a couple of REST API testing services

Added REST API testing in the general-purpose-test-automation-tools.md

---

php-test-automation.md

Added PHP Censor CI server.

---

java-test-automation.md

https://github.com/marcoslimaqa/sikuli-factory

Added SikuliFactory

---

java-test-automation.md

Please consider adding Beanmother :)

add beanmother

---

c#-test-automation.md

Wouldn't normally consider adding static site generators to this section, but this is the first one I've come across that can generate API docs without extra tooling.

Added Wyam to C# Documentation Generation section.

---

php-test-automation.md

Added Infection for PHP

---

php-test-automation.md

Added PHPSpec for PHP

---

php-test-automation.md

Added SensioLabs Security Checker for PHP.

Added SensioLabs Security Checker for PHP

---

php-test-automation.md

Added Sismo CI for PHP

---

automation-and-testing-as-service.md
c#-test-automation.md
java-test-automation.md
javascript-test-automation.md
php-test-automation.md
python-test-automation.md
ruby-test-automation.md

Hey guys, just wanted to add Mailosaur to the list - hope it fits well 👍

Add Mailosaur (email testing service)

---

general-purpose-test-automation-tools.md

How about adding Restlet Client to the API testing tools list?

Suggestion to add Restlet Client

---

general-purpose-test-automation-tools.md

Beeceptor is a rest API proxy tool that can ease verification by mocking hosted APIs. PR to add it to the list.

Adding Beeceptor.com - A rest api intercepting and mocking service

---

java-test-automation.md

Added Mockito to Useful libs section

---

mobile-test-automation.md

previous link for macaca have changed

update macaca's link

---

python-test-automation.md

Added pull request as indicated by @polusok in issue #206

Add seleniumbase to python web UI test automation

---

ruby-test-automation.md

- rename factory_girl to factory_bot

Add pronto, rbenv, brakeman, bundle-audit to Ruby

---

ruby-test-automation.md

Update capybara repo link

---

java-test-automation.md

Added test data section with an entry for Faker lib

Added Test Data Section

---

javascript-test-automation.md

Added [Differencify](https://github.com/NimaSoroush/differencify) - A library for visual regression testing

Added Differencify

---

general-purpose-test-automation-tools.md

Added link to GMeter

---

java-test-automation.md

This PR closes issue #186 (add retrofit to java)

Fix #186 - Retrofit

---

python-test-automation.md

This PR closes issue #247 (add fsociety to python)

Fix #247 - fsociety

---

python-test-automation.md

This PR closes #254 (add mitmproxy to python)

Fix #254 - mitmproxy

---

kotlin-test-automation.md

This PR closes issue #271 (add kukumber to kotlin)

Fix #271 - Kukumber

---

python-test-automation.md

This PR closes issue #277 (add stestr to python)

Fix #277 - stestr

---

python-test-automation.md

This PR closes issue #281 (add pytest-tricks in python)

Fix #281 - pytest-tricks

---

python-test-automation.md

This PR closes issue #289 (add retrying in python)

Fix #289 - retrying

---

general-purpose-test-automation-tools.md

This PR closes issue #256 (added AutoIt in general test automation tools)

Fix #256 - AutoIt

---

python-test-automation.md

This pull request closes issue #282

Fix #282 - extratools

---

javascript-test-automation.md

Add a new item to the list of test runner.
[tupe](https://github.com/jl-/tupe)

Add a new test runner: tupe

---

java-test-automation.md

TDD \ ATDD \ BDD
* Gauge
Web UI test automation
* Carina
* NoraUi
* TrueAutomation.IO
Security checking
* BDD-Security
Reporting
* Zafira

Add test automation frameworks for Java

---

javascript-test-automation.md

Web UI test automation
* Serenity/JS
* Chimpy.js
Mobile test automation
* Detox
* Cavy
Reporting
* cucumber-html-reporter

Add test automation frameworks for JavaScript

---

python-test-automation.md

Airtest is a Google Official announced Open Source Automated Testing Solution.
In my opinion it's an awesome automation test framework and easy to use for QA people, so I want to share with others. 
Thanks.

Add Airtest automation test framework

---

python-test-automation.md

added Golem to Python Automation frameworks

---

general-purpose-test-automation-tools.md

Testsigma is a functional testing tool and it has not been added to the list yet. Kindly add it to the list.

added testsigma tool to Functional Testing tools

---

ruby-test-automation.md

https://github.com/kapoorlakshya/screen-recorder

Add screen-recorder gem to Ruby/useful libs.

---

python-test-automation.md

Add pytest-play, play_selenium, play_requests and pypom_form project links

Update python test automation links

---

javascript-test-automation.md

A browser JavaScript testing toolkit for test automation

Add Buster.js test tool

---

python-test-automation.md

Fix #316 - Add Loguru to Python

---

python-test-automation.md

Fix #255 - Add Python-MSS to Python

---

java-test-automation.md

Fix #280 - Add Greenmail to Useful Libs

---

java-test-automation.md

Hello! 
I'd like [Mykhailo Poliarush](https://github.com/poliarush) to add [Image-Comparison](https://romankh3.github.io/image-comparison/) as a useful library to your awesome-test-automation.
cc [Dmytro Zharii](https://github.com/dzharii)
Best regards,
Roman.

added image-comparison as a useful library

---

java-test-automation.md
kotlin-test-automation.md

Added:
* Spock
* AssertJ
* Google Truth
* Spek

update java frameworks

---

java-test-automation.md

Added WinAppDriver under windows tools. As it is a defacto for windows automation recently.

Added WinAppDriver under windows tools.

---

python-test-automation.md

Add model-mommy: https://github.com/vandersonmota/model_mommy
Add django-test-plus: https://github.com/revsys/django-test-plus

Add model-mommy and django-test-plus to TDD \ ATDD \ BDD section

---

general-purpose-test-automation-tools.md
python-test-automation.md

Hello :) Here is a project that I am working on during the last few months - it is written in Python and has Python API, but also could be used as a command-line tool with apps written in any language - thats why I put it into two sections, is it ok? :)

Add Schemathesis

---

python-test-automation.md

I suggest adding `jsonschema`. It is very useful when validating data structures in JSON (e.g. when testing REST APIs).

Add jsonschema to python-test-automation.md

---

javascript-test-automation.md

Very useful library to generate test data

add faker js library as a useful lib

---

ruby-test-automation.md

1) Added Appium in Mobile test automation section.
2) Change link for Calabash, because link non active.
3) Added asdf-vm in Virtual environments section.
4) Added Yandex.Tank in Performance & stress & load section
5) Added Teamcity and Jenkins in Continuous Integration section
6) Added Rubymine, Visual Studio Code, Sublime text, Atom, Vim, Emacs in Editors, IDE, consoles section
7) Added guru99.com in Websites section

Added tools and descriptions

---

php-test-automation.md

[JakubOnderka/PHP-Parallel-Lint](https://github.com/JakubOnderka/PHP-Parallel-Lint) has been marked as abandoned and has been replaced by [php-parallel-lint/PHP-Parallel-Lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint).

Replace JakubOnderka/PHP-Parallel-Lint

---

mobile-test-automation.md

Add XCUITest framework for iOS app automation

Add XCUITest for iOS automation

---

java-test-automation.md

Add PowerMock under Java mocking libraries

Add PowerMock under Java mocking libraries

---

kotlin-test-automation.md

Add Strikt assertion library for Kotlin

Add Strikt assertion library for Kotlin

---

general-purpose-test-automation-tools.md

Add Insomnia under API testing tools

Add Insomnia under API testing tools

---

automation-and-testing-as-service.md

Add vREST under cloud based API testing solutions

Add vREST under cloud based API testing solutions

---

mobile-test-automation.md

remove Calabash from mobile-test-automation

---

java-test-automation.md
mobile-test-automation.md

- Adding more iOS and Android Native Stuffs
- Added CI options for Mobile
- Adding more mobile device cloud options
- Adding Katalon as an option for Hybrid development
- For Java added another CI, another IDE and removed dup info

Adding more mobile related stuffs, adding CI and IDE for Java and removing DUP

---

javascript-test-automation.md

Thanks for putting these awesome lists together 😊

Add QA Wolf to 'Web UI test automation' list

---

python-test-automation.md

Docs: https://wemake-python-stylegui.de
Repo: https://github.com/wemake-services/wemake-python-styleguide

Adds wemake-python-styleguide

---

mobile-test-automation.md

Add:
* [Kaspresso](https://github.com/KasperskyLab/Kaspresso) Kaspresso is a great framework for UI testing. Based on Espresso and UI Automator, Kaspresso provides a wide range of additional amazing features.

Add Kaspresso as mobile automation framework for android

---

javascript-test-automation.md

- added PactumJS to API Automation Testing

added PactumJS under API Automation in JavaScript

---

general-purpose-test-automation-tools.md
python-test-automation.md

[Mockintosh](https://mockintosh.io/) is a mock server generator that's capable to generate RESTful APIs and communicate with the message queues to mimick asynchronous tasks.

Add Mockintosh

---

general-purpose-test-automation-tools.md

Add Apitest under general purpose test automation tools,

Add apitest

---

java-test-automation.md

Added:
- https://github.com/RSheremeta/TestRail-JUnit - This Library helps you to integrate your JUnit-based tests with TestRail in an easily manner. 
- https://github.com/RSheremeta/TestRail-TestNG - This Library helps you to integrate your TestNG-based tests with TestRail in an easily manner.
- https://github.com/RSheremeta/Allure-Environment-Creator - This tiny Library helps you to serve and store environment data for Allure easily.

Added few items to "Java useful libs" list

---

general-purpose-test-automation-tools.md

I thought [cloudquery](https://github.com/cloudquery/cloudquery) might be a good fit here.

Add cloudquery to security testing

---

c#-test-automation.md
java-test-automation.md

Add:
- [Ocaramba](https://github.com/ObjectivityLtd/Ocaramba) 
- [Ocaramba.templates](https://github.com/ObjectivityLtd/Ocaramba.templates)
- [CRUX](https://github.com/ObjectivityLtd/crux) 
DataBase test automation
- [NBi](https://github.com/Seddryck/NBi)
- [DBTestCompare](https://github.com/ObjectivityLtd/DBTestCompare)
- [DBTestCompareGenerator](https://github.com/ObjectivityLtd/DBTestCompareGenerator)

Add DataBase test automation, C# Ocaramba Web driver framework, Crux - performance tool

---

c#-test-automation.md

https://docs.microsoft.com/en-us/visualstudio/test/use-ui-automation-to-test-your-code?view=vs-2019
"Coded UI Test for automated UI-driven functional testing is deprecated. Visual Studio 2019 is the last version where Coded UI Test will be fully available."

Code Ui is deprecated

---

general-purpose-test-automation-tools.md
python-test-automation.md

Add httprunner API Testing Framework which is a good one.

Add httprunner API Testing Framework

---

python-test-automation.md

Add tavern in API testing frameworks.

Add tavern framework

---

java-test-automation.md

Added TestZeus as resource for Salesforce Test Automation

Added resource for Salesforce Test Automation

---

general-purpose-test-automation-tools.md

Hi there. This PR adds a newly open-sourced regression test automation solution to the list of general purpose functional testing tools.

Add Touca as general purpose tool for functional testing

---

python-test-automation.md

Added Poetry in python-test-automation.md

---

java-test-automation.md

Adding a link to Instancio: https://github.com/instancio/instancio/

Add link to Instancio

---

python-test-automation.md

Add new python linter

---

automation-and-testing-as-service.md

@poliarush I noticed LambdaTest also have a PR on the same file. Would it make your life easier if I merged these into 1 PR?
I have personal experience using LambdaTest so can confirm they're a valid addition.

Added DoesQA to Web test automation and testing

---

kotlin-test-automation.md

Add kotlin-faker to 'kotlin useful libs'

---

general-purpose-test-automation-tools.md

Promoting Apache JMeter to Load testing tools.

Add [Apache Jmeter] in Load testing tools

---

c#-test-automation.md

Resolved #476 
Add NBomber to C# test automation section

Add NBomber to C# test automation
